language: generic

services:
  - docker

before_install:
  - docker build -t emirhanaydin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true emirhanaydin/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-399087810341'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
